### ISSUE TITLE
With Flutter 3.7.0 the shadow moves very far from the object

### ISSUE THREAD

**Issue by mark8044** [marcelopmont/simple_shadow#5]
It seems like the Offset property isn't working properly on Flutter 3.7.0. It moves very far away from the container, but if you do a hot reload it will come back to where it is supposed to be. Its strange behavior, sometimes there on initial load then fixes it self with reloads

**Comment by mark8044** [comment]
I personally feel this is a bug with flutter itself, since your code and implementation of Offset is quite straightforward

**Comment by matt-hall-zory** [comment]
I've found the position flickering from where it's supposed to be and back if there is any animation.

**Comment by mark8044** [comment]
> I've found the position flickering from where it's supposed to be and back if there is any animation.

Yup, very similar, it will go back sometimes, in my case if its in a listview and I do a pull to refresh it goes back.   I never noticed it in 3.3.10, so I think it has to do with 3.7

**Comment by neuttt** [comment]
![image](https://user-images.githubusercontent.com/88629701/216230541-cecc9ce0-73f8-43ae-ae8a-898449e37092.png)

**Comment by popoch** [comment]
Once I upgrade my flutter to 3.7.1, the problem is solved.

**Comment by neuttt** [comment]
Flutter 3.7.1

- Material 3 Navigation Drawer does not support scrolling or safe areas
- ImageFilter in ListView causes wrong offset on Android and iOS <<<<<<<
- CastError when running flutter pub get
- fonts are blurry when rendering on iOS
- objects with large stroke width not drawn correctly on iOS
- text is transformed incorrectly on iOS
- draw calls could be improperly culled
- Float samplers can get re-ordered compared to SkSL
- replace iPhone 6s with iPhone 11 as flutter test devices

**Comment by mark8044** [comment]
> Once I upgrade my flutter to 3.7.1, the problem is solved.

I believe it is solved with 3.7.1 for me as well, I have not extensively tested it yet, but will do so over the next few days

**Comment by arioul89** [comment]
Solved for me as well after updating to 3.7.1.

**Comment by mark8044** [comment]
Ok it looks like it is solved for a few people, so I will close this issue.  For anyone looking here, the solution is to upgrade to Flutter 3.7.1
